name: Build Verification Tests

on:
  deployment_status:

jobs:
  tests:
    if: ${{ github.event.deployment_status.state == 'success' }}  
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - title: Chrome Windows
            suite: chrome-win
          - title: Firefox Windows
            suite: firefox-win
          - title: Chrome Android
            suite: chrome-android
          - title: Safari iOS
            suite: safari-ios
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
        with:
          sha: ${{ github.sha }}
          filterOutClosed: true
      - name: Checkout (including submodules)
        uses: actions/checkout@v3
        if: steps.PR.outputs.pr_found == 'true'
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v3
        if: steps.PR.outputs.pr_found == 'true'
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Run tests
        if: steps.PR.outputs.pr_found == 'true'
        env:
          MAIN_PAGE_URL: ${{ github.event.deployment_status.target_url }}
          SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}
          SAUCELABS_PASSWORD: ${{ secrets.SAUCELABS_PASSWORD }}
        run: |
          cd tests/e2e
          ./gradlew runStories -Pvividus.web-application.main-page-url=${MAIN_PAGE_URL} \
                               -Pvividus.selenium.grid.username=${SAUCELABS_USERNAME} \
                               -Pvividus.selenium.grid.password=${SAUCELABS_PASSWORD} \
                               -Pvividus.configuration-set.active=${{ matrix.suite }} \
                               -Pvividus.allure.executor.name="Github Actions (DxP)" \
                               -Pvividus.allure.executor.type=github \
                               -Pvividus.allure.executor.url=https://github.com/dxp-prototype/dxp-proto/actions \
                               -Pvividus.allure.executor.build-order=${GITHUB_RUN_ID} \
                               -Pvividus.allure.executor.build-name="Build Verification Tests ${GITHUB_RUN_ID}" \
                               -Pvividus.allure.executor.build-url=https://github.com/dxp-prototype/dxp-proto/actions/runs/${GITHUB_RUN_ID} \
                               -Pvividus.allure.executor.report-url=https://github.com/dxp-prototype/dxp-proto/actions/runs/${GITHUB_RUN_ID} \
                               -Pvividus.allure.executor.report-name="Build Verification report"
      - name: Publish web application tests report
        if: always() && steps.PR.outputs.pr_found == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: Tests report for ${{ matrix.suite }} run
          path: tests/e2e/output/reports/allure
      - name: Deploy report to Vercel
        if: always() && steps.PR.outputs.pr_found == 'true'
        env:
          REPORT_DEPLOY_KEY: ${{ secrets.REPORT_DEPLOY_KEY }}
          VERCEL_ORG_ID: ${{ vars.REPORT_VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.REPORT_VERCEL_PROJECT_ID }}
        run: |
          mkdir report_links
          DEPLOYMENT_FILE=${{ github.workspace }}/report_links/${{ matrix.suite }}.txt

          cd tests/e2e/
          mv output/reports/allure .
          cd allure

          npm install -g vercel
          vercel deploy -t $REPORT_DEPLOY_KEY -S jnj-demo-account > $DEPLOYMENT_FILE
          echo -n "|${{ matrix.title }}" >> $DEPLOYMENT_FILE
          status=$([[ "${{ job.status }}" == "success" ]] && echo ":white_check_mark:" || echo ":x:")
          echo -n "|${status}" >> $DEPLOYMENT_FILE
      - uses: actions/upload-artifact@master
        if: always() && steps.PR.outputs.pr_found == 'true'
        with:
          path: report_links/${{ matrix.suite }}.txt
      - name: Publish web application tests report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Tests report for ${{ matrix.suite }} run
          path: tests/e2e/output/reports/allure
  playwright:
    if: ${{ github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Get PR info
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
        with:
          sha: ${{ github.sha }}
          filterOutClosed: true
      - name: Checkout (including submodules)
        uses: actions/checkout@v3
        if: steps.PR.outputs.pr_found == 'true'
      - name: Install Node
        uses: actions/setup-node@v3
        if: steps.PR.outputs.pr_found == 'true'
        with:
          node-version: 16.19.1
          cache: 'npm'
      - name: Build
        if: steps.PR.outputs.pr_found == 'true'
        run: |
          npm install
          npm run build
      # Cache playwright installation blocker https://github.com/actions/cache/issues/319
      - name: Run playwright tests
        if: steps.PR.outputs.pr_found == 'true'
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
        run: |
          if [ "${{ steps.PR.outputs.pr_found }}" == "true" ]; then
            export APPLITOOLS_BATCH_NAME="${{ steps.PR.outputs.pr_title }} (${{ steps.PR.outputs.number }})"
          fi
          export DEBUG=pw:webserver
          npx playwright install --with-deps
          npm run test:smoke
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Generate Applitools report links
        if: always() && steps.PR.outputs.pr_found == 'true'
        run: |
          mkdir report_links
          status=$([[ "${{ job.status }}" == "success" ]] && echo ":white_check_mark:" || echo ":x:")
          declare -a batchLinks
          batchLinks=($(find test-results -name "visual-test-*" -exec cat {} \; | uniq))
          for batchLink in "${batchLinks[@]}"; do
            declare outputFile=$(openssl rand -hex 10)
            echo "${batchLink}|Applitools Report|${status}" >> report_links/${outputFile}.txt
          done
      - uses: actions/upload-artifact@master
        if: always() && steps.PR.outputs.pr_found == 'true'
        with:
          path: report_links/*
  report:
    if: always()
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: [ tests, playwright ]
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
        with:
          sha: ${{ github.sha }}
          filterOutClosed: true
      - name: Download file
        if: steps.PR.outputs.pr_found == 'true'
        uses: actions/download-artifact@v3
        with:
          path: report_links
      - name: Format
        if: steps.PR.outputs.pr_found == 'true'
        run: |
          echo '## :fire: Build Verification Tests Report :fire:' > comment.txt
          cd report_links/artifact/
          declare -a artifacts=(*)
          for artifact in "${artifacts[@]}"; do
            declare title=$(cat ${artifact} | cut -d '|' -f2)
            declare link=$(cat ${artifact} | cut -d '|' -f1)
            declare symbol=$(cat ${artifact} | cut -d '|' -f3)
            echo "* ${symbol}[${title}](${link})" >> ${{ github.workspace }}/comment.txt
          done
      - name: Add test report comment
        uses: thollander/actions-comment-pull-request@v2
        if: steps.PR.outputs.pr_found == 'true'
        with:
          filePath: comment.txt
          reactions: eyes
          mode: recreate
          comment_tag: test_report
          pr_number: ${{ steps.PR.outputs.number }}
