name: End to End Tests

on:
  deployment_status:

jobs:
  tests:
    if: ${{ github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - title: Chrome Windows
            suite: chrome-win
          - title: Firefox Windows
            suite: firefox-win
          - title: Chrome Android
            suite: chrome-android
          - title: Safari iOS
            suite: safari-ios
    steps:
      - name: Checkout (including submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Run tests
        env:
          MAIN_PAGE_URL: ${{ github.event.deployment_status.target_url }}
          SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}
          SAUCELABS_PASSWORD: ${{ secrets.SAUCELABS_PASSWORD }}
        run: |
          cd tests/e2e
          ./gradlew runStories -Pvividus.web-application.main-page-url=${MAIN_PAGE_URL} \
                               -Pvividus.selenium.grid.username=${SAUCELABS_USERNAME} \
                               -Pvividus.selenium.grid.password=${SAUCELABS_PASSWORD} \
                               -Pvividus.configuration-set.active=${{ matrix.suite }}
      - name: Deploy report to Vercel
        if: always()
        env:
          REPORT_DEPLOY_KEY: ${{ secrets.REPORT_DEPLOY_KEY }}
        run: |
          mkdir deployments
          DEPLOYMENT_FILE=${{ github.workspace }}/deployments/${{ matrix.suite }}.txt

          cd tests/e2e/
          mv output/reports/allure .
          cp -r .vercel allure
          cd allure

          npm install -g vercel
          vercel deploy -t $REPORT_DEPLOY_KEY -S jnj-demo-account > $DEPLOYMENT_FILE
          echo -n "|${{ matrix.title }}" >> $DEPLOYMENT_FILE
          status=$([[ "${{ job.status }}" == "success" ]] && echo ":white_check_mark:" || echo ":x:")
          echo -n "|${status}" >> $DEPLOYMENT_FILE
      - uses: actions/upload-artifact@master
        if: always()
        with:
          path: deployments/${{ matrix.suite }}.txt
      - name: Publish web application tests report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Tests report for ${{ matrix.suite }} run
          path: tests/e2e/output/reports/allure
  report:
    if: always()
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      pull-requests: write
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
        with:
          sha: ${{ github.sha }}
          filterOutClosed: true
      - name: Download file
        if: steps.PR.outputs.pr_found == 'true'
        uses: actions/download-artifact@v3
        with:
          path: deployments
      - name: Format
        if: steps.PR.outputs.pr_found == 'true'
        run: |
          echo '## :fire: End To End Tests Report :fire:' > comment.txt
          cd deployments/artifact/
          declare -a artifacts=(*)
          for artifact in "${artifacts[@]}"; do
            declare title=$(cat ${artifact} | cut -d '|' -f2)
            declare link=$(cat ${artifact} | cut -d '|' -f1)
            declare symbol=$(cat ${artifact} | cut -d '|' -f3)
            echo "* ${symbol}[${title}](${link})" >> ${{ github.workspace }}/comment.txt
          done
      - name: Add test report comment
        uses: thollander/actions-comment-pull-request@v2
        if: steps.PR.outputs.pr_found == 'true'
        with:
          filePath: comment.txt
          reactions: eyes
          mode: recreate
          comment_tag: test_report
          pr_number: ${{ steps.PR.outputs.number }}
