name: Build Knapsack Listerine
env:
  CI: true
  FORCE_COLOR: 1

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js v16.14
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
      - name: Setup & Build
        run: npm install && npm run build:knapsack
