name: Product Publish
env:
  CI: true
  CONTENT_PUBLISH_GIT_USERNAME: ${{ secrets.CONTENT_PUBLISH_GIT_USERNAME }}
  CONTENT_PUBLISH_GIT_PASSWORD: ${{ secrets.CONTENT_PUBLISH_GIT_PASSWORD }}
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  CONTENT_PUBLISH_BASE_BRANCH: ${{ vars.CONTENT_PUBLISH_BASE_BRANCH }}
on:
  workflow_dispatch:
  repository_dispatch:
    types: [product-publish]
concurrency: content-publish
jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'product-publish' }}
    steps:
      - uses: actions/checkout@v3
      - name: Git info
        run: git remote -v
      - name: Use node v16.14
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
      - name: Cache DXP build
        id: cache-dxp-build
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ./packages
            ./sites
          key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}-${{ hashFiles('packages/**/src') }}
      - if: ${{ steps.cache-dxp-build.outputs.cache-hit != 'true' }}
        name: Setup and build packages
        run: npm install && npm run build
      - name: Publish
        run: npm run build:content-publish -- --script 'cd sites/__dxp__/ && npm run build:fetch-products'

    
